service: crypto-chatbot

provider:
  name: aws
  runtime: python3.8

functions:
  send_crypto_rates:
    handler: handler.lambda_handler
    events:
      - schedule: rate(1 hour)
    environment:
      YOUR_TELEGRAM_BOT_TOKEN: ${self:custom.dotenv.YOUR_TELEGRAM_BOT_TOKEN, env:YOUR_TELEGRAM_BOT_TOKEN, ''}
      BINANCE_API_KEY: ${env:BINANCE_API_KEY, self:custom.dotenv.BINANCE_API_KEY, ''}
      BINANCE_API_SECRET: ${env:BINANCE_API_SECRET, self:custom.dotenv.BINANCE_API_KEY, ''}
      COINBASE_API_KEY: ${env:COINBASE_API_KEY, self:custom.dotenv.COINBASE_API_KEY, ''}
      COINBASE_API_SECRET: ${env:COINBASE_API_SECRET, self:custom.dotenv.COINBASE_API_SECRET, ''}
      WHATSAPP_USERS: ${env:WHATSAPP_USERS, self:custom.dotenv.WHATSAPP_USERS, ''}
      TELEGRAM_CHAT_IDS: ${env:TELEGRAM_CHAT_IDS, self:custom.dotenv.TELEGRAM_CHAT_IDS, ''}
      SKIP_QR_CODE: true  # Set this variable to "true" to skip QR

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
  pythonRequirements:
    dockerizePip: non-linux

