name: test-sls-release

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AWS_ROLE_ARN: arn:aws:iam::443420183404:role/github
  AWS_DEFAULT_REGION: us-east-1
  PLAN_NAME: main
  SLS_VERSION: '3.28.0'
  NODE_VERSION: '16.17.0'
  PYTHON_VERSION: '3.9'
  # SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
  YOUR_TELEGRAM_BOT_TOKEN: ${{ secrets.YOUR_TELEGRAM_BOT_TOKEN }}
  BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
  BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
  COINBASE_API_KEY: ${{ secrets.COINBASE_API_KEY }}
  COINBASE_API_SECRET: ${{ secrets.COINBASE_API_SECRET }}
  YOUR_TWILIO_ACCOUNT_SID: ${{ secrets.YOUR_TWILIO_ACCOUNT_SID }}
  YOUR_TWILIO_AUTH_TOKEN: ${{ secrets.YOUR_TWILIO_AUTH_TOKEN }}
  YOUR_TWILIO_PHONE_NUMBER: ${{ secrets.YOUR_TWILIO_PHONE_NUMBER }}
  YOUR_WHATSAPP_NUMBER: ${{ secrets.YOUR_WHATSAPP_NUMBER }}
  
permissions:
  contents: write 
  issues: write 
  pull-requests: write 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Serverless Framework
        run: npm install -g serverless@${{env.SLS_VERSION}}
      # - name: Install Python dependencies
      #   run: pip install -r requirements.txt
      - name: Install required sls plugins
        run: |
          serverless plugin install -n serverless-python-requirements
          serverless plugin install -n serverless-offline
          serverless plugin install -n serverless-dotenv-plugin
      - name: Test Telegram handler
        run: |
          serverless invoke local --function telegram
      - name: Test crypto rates handler
        run: python get_crypto_rates.py BTC Binance
      # - name: Test WhatsApp handler
      #   run: python tests/test_whatsapp_handler.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Install Serverless Framework
        run: npm install -g serverless@${{env.SLS_VERSION}}
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install required sls plugins
        run: |
          serverless plugin install -n serverless-python-requirements
          serverless plugin install -n serverless-offline
          serverless plugin install -n serverless-dotenv-plugin
      - name: Package Serverless
        run: sls package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{env.AWS_ROLE_ARN}}
          role-session-name: testrolesession
          aws-region: ${{env.AWS_DEFAULT_REGION}}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Deploy Serverless
        run: sls deploy
